# Generated by Django 3.2.7 on 2021-09-29 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
