# Generated by Django 3.2.7 on 2021-09-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20210929_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_pic_path',
            field=models.CharField(default='default_cover.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic_path',
            field=models.CharField(default='default_profile.png', max_length=200),
        ),
    ]
