# Generated by Django 3.2.7 on 2021-10-01 17:21

from django.db import migrations, models
import user_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_profile.png', upload_to=user_auth.models.Profile.image_dir),
        ),
    ]
