# Generated by Django 3.2.7 on 2021-10-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_auto_20211001_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_pic_path',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic_path',
        ),
    ]
