# Generated by Django 3.1 on 2021-10-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0016_friend'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('from_user', 'to_user')},
        ),
    ]
