# Generated by Django 3.1 on 2021-10-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_and_like', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
