# Generated by Django 3.1 on 2021-10-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_and_like', '0002_auto_20211004_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
