# Generated by Django 3.1 on 2021-10-04 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0015_auto_20211003_1748'),
        ('posts_and_like', '0005_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.profile')),
                ('on_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts_and_like.post')),
            ],
        ),
    ]
