# Generated by Django 3.1 on 2021-10-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_and_like', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
